# Generated by Django 5.0.11 on 2025-03-20 06:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+917807455055', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
