# Generated by Django 5.0.11 on 2025-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_access_phonenumber_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
