# Generated by Django 5.0.11 on 2025-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_adminlog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
