# Generated by Django 5.0.11 on 2025-03-23 15:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_access_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+917807455055', max_length=128, null=True, region=None, unique=True),
        ),
    ]
