# Generated by Django 5.0.11 on 2025-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='UserEmail',
            field=models.EmailField(default='demouser@ciimcmalpha.org', max_length=254, unique='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Username',
            field=models.CharField(default='USer', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
