# Generated by Django 5.0.11 on 2025-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_request_useremail_request_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='Email',
            field=models.EmailField(default='demo@ciimcm.org', max_length=254),
        ),
    ]
