# Generated by Django 5.0.11 on 2025-03-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_alter_adminlog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='Reinstated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='access',
            name='Reinstated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
