# Generated by Django 5.0.11 on 2025-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_access_reinstated_access_reinstated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Issued_By',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Post',
            field=models.CharField(choices=[('student', 'Student'), ('trainer', 'Trainer')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Quantity',
            field=models.IntegerField(default=0, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='Returned_To',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Tool_Name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='Return_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='UserEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
