# Generated by Django 5.0.11 on 2025-04-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_request_issued_by_request_post_request_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='request',
            name='IssuedQuantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='ReturnQuantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
