# Generated by Django 5.0.11 on 2025-04-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_remove_request_quantity_request_issuedquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Authorized_By',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
