# Generated by Django 5.0.11 on 2025-04-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0011_request_authorized_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labequipment',
            old_name='added_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='labequipment',
            name='lab_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labequipment',
            name='requested_by',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='labequipment',
            name='tool_name',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
