# Generated by Django 5.0.11 on 2025-04-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0012_rename_added_at_labequipment_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
