# Generated by Django 5.0.11 on 2025-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0013_alter_lab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Lab_Name',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='LabId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Section',
            field=models.CharField(choices=[('et', [('Electrical Technician', 'Electrical Technician'), ('CCTV', 'CCTV'), ('Solar', 'Solar'), ('Motor Starter', 'Motor Starter'), ('Cabling Technician', 'Cabling Technician'), ('EV Charging', 'EV Charging'), ('Energy Meter', 'Energy Meter')]), ('beauty', [('Skin', 'Skin'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup')]), ('stitch', [('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Knitting', 'Knitting')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Section',
            field=models.CharField(choices=[('et', [('Electrical Technician', 'Electrical Technician'), ('CCTV', 'CCTV'), ('Solar', 'Solar'), ('Motor Starter', 'Motor Starter'), ('Cabling Technician', 'Cabling Technician'), ('EV Charging', 'EV Charging'), ('Energy Meter', 'Energy Meter')]), ('beauty', [('Skin', 'Skin'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup')]), ('stitch', [('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Knitting', 'Knitting')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='Section',
            field=models.CharField(choices=[('et', [('Electrical Technician', 'Electrical Technician'), ('CCTV', 'CCTV'), ('Solar', 'Solar'), ('Motor Starter', 'Motor Starter'), ('Cabling Technician', 'Cabling Technician'), ('EV Charging', 'EV Charging'), ('Energy Meter', 'Energy Meter')]), ('beauty', [('Skin', 'Skin'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup')]), ('stitch', [('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Knitting', 'Knitting')])], max_length=100),
        ),
    ]
