# Generated by Django 5.0.11 on 2025-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0014_equipment_lab_name_lab_labid_alter_equipment_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Section',
            field=models.CharField(choices=[('Create New Section', 'Create New Section'), ('et', [('Electrical Technician', 'Electrical Technician'), ('CCTV', 'CCTV'), ('Solar', 'Solar'), ('Motor Starter', 'Motor Starter'), ('Cabling Technician', 'Cabling Technician'), ('EV Charging', 'EV Charging'), ('Energy Meter', 'Energy Meter')]), ('beauty', [('Skin', 'Skin'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup')]), ('stitch', [('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Knitting', 'Knitting')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Section',
            field=models.CharField(choices=[('Create New Section', 'Create New Section'), ('et', [('Electrical Technician', 'Electrical Technician'), ('CCTV', 'CCTV'), ('Solar', 'Solar'), ('Motor Starter', 'Motor Starter'), ('Cabling Technician', 'Cabling Technician'), ('EV Charging', 'EV Charging'), ('Energy Meter', 'Energy Meter')]), ('beauty', [('Skin', 'Skin'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup')]), ('stitch', [('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Knitting', 'Knitting')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='Section',
            field=models.CharField(choices=[('Create New Section', 'Create New Section'), ('et', [('Electrical Technician', 'Electrical Technician'), ('CCTV', 'CCTV'), ('Solar', 'Solar'), ('Motor Starter', 'Motor Starter'), ('Cabling Technician', 'Cabling Technician'), ('EV Charging', 'EV Charging'), ('Energy Meter', 'Energy Meter')]), ('beauty', [('Skin', 'Skin'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Makeup', 'Makeup')]), ('stitch', [('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Knitting', 'Knitting')])], max_length=100),
        ),
    ]
