# Generated by Django 5.0.11 on 2025-05-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0015_alter_equipment_section_alter_lab_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('et', 'ET'), ('beauty', 'Beauty'), ('stitch', 'Stitch')], max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventoryapp.section'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labs', to='inventoryapp.section'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request', to='inventoryapp.section'),
        ),
    ]
